import { Metadata } from "next";
import "../globals.css";
import RootLayoutClient from "./rootLayoutClient";

export const metadata: Metadata = {
  title: "Website SID Desa Kab. Sumedang",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return <RootLayoutClient>{children}</RootLayoutClient>;
}
